name: Ready to Merge

on:
  pull_request:
    types: [labeled, unlabeled]
    branches:
      - main

jobs:
  # Check if the PR has the required labels denoting it is ready to merge.
  # Automatically passes for non-CMS tickets.
  has-required-labels:
    name: Check for Required Labels
    runs-on: ubuntu-latest
    permissions:
      # Needed to create PR statuses/checks
      statuses: write
      checks: write
    steps:
      - name: Update check status
        uses: actions/github-script@v7
        with:
          script: |
            const ctx = {
              owner: context.repo.owner,
              repo: context.repo.repo,
            }
            const pr = context.payload.pull_request
            const prLabels = pr.labels.map((label) => label.name)

            // Only create a check for success. We'll use required checks to
            // determine if the PR is ready to merge without showing a failure.
            const requiredLabel = 'Ready to Merge'
            if (prLabels.includes(requiredLabel)) {
              await github.rest.checks.create({
                ...ctx,
                head_sha: pr.head.sha,
                name: `Marked as Ready to Merge`,
                status: 'completed',
                conclusion: 'success',
              })
            }
            console.log(
              `PR ${prLabels.includes(requiredLabel) ? 'has' : 'does not have'} required label: ${requiredLabel}`
            )
            return context.payload.client_payload.value
